/* Sample content for the Field Guide wiki UI kit.
   Not the real corpus — representative entries that exercise every
   component and the cross-link graph. Exposed as window.WIKI_DATA. */
window.WIKI_DATA = {
  sections: [
    { id: 'structure', label: 'Structure & Pacing', count: 31, icon: 'structure' },
    { id: 'puzzles',   label: 'Puzzles, Clues & Information', count: 27, icon: 'puzzles' },
    { id: 'story',     label: 'Story, Character & Voice', count: 34, icon: 'story' },
    { id: 'players',   label: 'Players & Social Dynamics', count: 24, icon: 'players' },
    { id: 'space',     label: 'Space, Props & Materiality', count: 18, icon: 'space' },
    { id: 'systems',   label: 'Systems & Mechanics', count: 24, icon: 'systems' },
  ],

  /* Each family is a PART; the part page integrates its PRIMER (title shown
     as the part's subtitle) then lists the numbered articles. Story's primer
     is still to be written. */
  primers: {
    structure: { part: 'A', title: 'The Shape of Time', lead: 'Every designed experience has a shape in time — a curve of tension, a loop, a branching tree. Before any scene is written, the designer is choosing a silhouette for the whole.' },
    puzzles:   { part: 'B', title: 'The Fairness Contract', lead: 'A puzzle is a promise: that an attentive solver, working only with what they were given, can get there from here. Everything in this family is built on keeping that promise.' },
    story:     { part: 'C', title: null, lead: 'The narrative and aesthetic layer — voice, character, world. The primer for this family is still being written.' },
    players:   { part: 'D', title: 'The Social Contract & Safety', lead: 'Before the game begins, the table agrees — often silently — on what is allowed, what is real, and how to stop. This family is about making that agreement deliberate.' },
    space:     { part: 'E', title: 'Making It Real', lead: 'The physical and sensory layer: the artefact in the hand, the lock that opens, the room that wraps the player. Where the game stops being described and starts being touched.' },
    systems:   { part: 'F', title: 'The Engine Room', lead: 'Underneath the fiction is the engine that decides what happens — dice, clocks, moves, economies. This family is about the machinery and the table-feel it produces.' },
  },
  facets: [
    { id: 'cluing', label: 'Cluing', count: 42 },
    { id: 'fairness', label: 'Fairness', count: 27 },
    { id: 'mood', label: 'Mood', count: 31 },
    { id: 'pacing', label: 'Pacing', count: 23 },
    { id: 'social', label: 'Social Contract', count: 18 },
    { id: 'failure', label: 'Failure Modes', count: 14 },
  ],
  entries: [
    {
      id: 'fairness-contract',
      number: 14,
      family: 'puzzles',
      taxon: 'Puzzles · Cluing & Information',
      title: 'Cluing & Fairness',
      provenance: 'researched',
      silhouette: 'The contract that says a solver who pays attention can get there from here.',
      media: 'if',
      plateCaption: 'The locked diorama — every clue placed in plain sight.',
      tags: ['Cluing', 'Fairness', 'Information'],
      body: [
        { type: 'lead', text: 'Cluing is the craft of handing over exactly enough to reach the answer and no more. A puzzle with no clues is a locked box with no keyhole; a puzzle with the wrong clues is a box with the answer painted on the lid. The work sits between those two failures.' },
        { type: 'p', text: 'Fairness is the promise underneath. An attentive person, working only with what the puzzle gave them, can reach the solution without guessing and without secret knowledge. The same promise wears four coats: "fair play" in a detective story, the "Three Clue Rule" at a tabletop, "no tricks" in a puzzle hunt.', prov: 'synthesis' },
        { type: 'h', text: 'The Mechanism' },
        { type: 'p', text: 'A puzzle is fair when a sufficiently attentive solver can reach the answer using only what the puzzle provides, plus any convention they had a way to find first. The test is reachability, not ease: a fair puzzle can still be brutally hard.', prov: 'corpus' },
        { type: 'h3', text: 'Every clue does work' },
        { type: 'p', text: 'Nothing on the page is decorative by accident. Anything a solver might take for a clue should either do real work or be deliberately neutral — and the convention has to hold. Let odd capitals hide a message in one puzzle and solvers will hunt for hidden messages forever after.', prov: 'corpus' },
        { type: 'callout', kind: 'specimen', title: 'MIT Mystery Hunt', text: 'Decades of a shared cluing grammar solvers carry between puzzles: answers arrive as all-caps phrases so metas can extract from them, a grid of exactly 26 entries probably means the alphabet, and the 2014 Hunt ruled flavour text was never required to solve — declared up front, so solvers knew where they stood.' },
        { type: 'h3', text: 'Indirection, not obscurity' },
        { type: 'p', text: 'The line that matters is between indirection and obscurity. Under indirection the solver works, yet every step reads clearly as a step once found. Under obscurity the path stays hidden even from full attention. The discipline is to make each move hard to make but easy to recognise once made.', prov: 'corpus' },
        { type: 'callout', kind: 'hazard', text: 'The seductive failure is the clever rule only you know. The tell is when your own playtest notes say "they should have realised" more than once — the designer\u2019s voice covering an unfair gap. The solver does not owe you the leap.' },
        { type: 'h', text: 'Where this fits' },
        { type: 'p', text: 'Fairness is the floor the rest of this family stands on. Once a puzzle is fair, the craft turns to the payoff fair cluing has earned — the aha moment — and, when fair clues still leave solvers stuck, to graceful hint systems and recovery.', prov: 'synthesis' },
        { type: 'sources', items: [
          'Wilson, D. "Introduction to Writing Good Puzzle Hunt Puzzles." MIT.',
          'Selinker & Snyder. Puzzlecraft. Lone Shark Games, 2012.',
          'Alexander, J. "The Three Clue Rule." The Alexandrian, 2008.',
          'Van Dine, S. S. "Twenty Rules for Writing Detective Stories." 1928.',
        ] },
      ],
      backlinks: [
        { title: 'Red Herrings & False Leads', taxon: 'Puzzles', id: 'red-herrings' },
        { title: 'The Locked-Room Mystery', taxon: 'Structure', id: 'locked-room' },
        { title: 'Diegetic Hint Systems', taxon: 'Story', id: 'diegetic-hints' },
      ],
      exemplar: {
        title: 'Return of the Obra Dinn',
        subtitle: 'Lucas Pope · 2018',
        rows: [
          { label: 'Medium', value: 'Deduction game' },
          { label: 'Mechanism', value: 'Memento mori watch' },
          { label: 'Cluing', value: 'Triangulation' },
          { label: 'Fairness', value: 'Verify-in-threes' },
        ],
      },
    },
    {
      id: 'red-herrings',
      number: 15,
      family: 'puzzles',
      taxon: 'Puzzles · Cluing & Information',
      title: 'Red Herrings & False Leads',
      silhouette: 'A lie the design tells on purpose — and must let the player catch.',
      media: 'tabletop',
      tags: ['Cluing', 'Fairness', 'Failure Modes'],
    },
    {
      id: 'diegetic-hints',
      number: 7,
      family: 'story',
      taxon: 'Story · Diegetic Design',
      title: 'Diegetic Hint Systems',
      silhouette: 'Help that arrives from inside the world, never from above it.',
      media: 'live',
      tags: ['Diegesis', 'Cluing', 'Immersion'],
    },
    {
      id: 'locked-room',
      number: 31,
      family: 'structure',
      taxon: 'Structure · Branching Topology',
      title: 'The Locked-Room Mystery',
      silhouette: 'A bounded world where the answer was always already inside.',
      media: 'if',
      tags: ['Information', 'Pacing', 'Fairness'],
    },
    {
      id: 'magic-circle',
      number: 2,
      family: 'players',
      taxon: 'Players · Trust & Pressure',
      title: 'The Magic Circle',
      silhouette: 'The invisible line a player steps across to agree the game is real.',
      media: 'tabletop',
      tags: ['Social Contract', 'Safety'],
    },
    {
      id: 'dread-pacing',
      number: 22,
      family: 'structure',
      taxon: 'Structure · Pacing & Energy',
      title: 'The Architecture of Dread',
      silhouette: 'Fear is a tempo, not a monster.',
      media: 'live',
      tags: ['Pacing', 'Tension', 'Mood'],
    },
  ],
};
