#!/usr/bin/env python3
"""Inject 'Referenced by' backlink sections into content/**/*.qmd.

Scans every renderable file for outbound markdown links to other .qmd files,
builds the reverse index, and writes an idempotent, marker-delimited
'## Referenced by' block at the foot of each linked-to file. Re-running with
no link changes is a no-op (byte-identical), so the build does not churn git.

Runs as the Quarto pre-render step (see _quarto.yml).
"""
import os
import re
import pathlib

CONTENT = pathlib.Path("content")
START = "<!-- BACKLINKS:START (generated by scripts/backlinks.py — do not edit by hand) -->"
END = "<!-- BACKLINKS:END -->"

# [label](path.qmd) and [label](path.qmd#anchor); ignore pure anchors and externals.
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)#]+\.qmd)(?:#[^)]*)?\)")
BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END) + r"\n*", re.S)
TITLE_RE = re.compile(r'^title:\s*"?(.*?)"?\s*$', re.M)


def title_of(path: pathlib.Path) -> str:
    m = TITLE_RE.search(path.read_text(encoding="utf-8")[:800])
    return m.group(1).strip() if m else path.stem


def strip_block(text: str) -> str:
    return BLOCK_RE.sub("", text).rstrip() + "\n"


def main() -> None:
    files = sorted(CONTENT.rglob("*.qmd"))
    by_resolved = {f.resolve(): f for f in files}

    inbound = {f: set() for f in files}
    for src in files:
        body = strip_block(src.read_text(encoding="utf-8"))
        for _label, target in LINK_RE.findall(body):
            tp = (src.parent / target).resolve()
            dst = by_resolved.get(tp)
            if dst is not None and dst != src:
                inbound[dst].add(src)

    changed = 0
    for tgt, srcs in inbound.items():
        text = tgt.read_text(encoding="utf-8")
        base = strip_block(text)
        if srcs:
            items = sorted((title_of(s), os.path.relpath(s, tgt.parent)) for s in srcs)
            block = [START, "", "## Referenced by", ""]
            block += [f"- [{t}]({r})" for t, r in items]
            block += ["", END]
            new = base.rstrip() + "\n\n" + "\n".join(block) + "\n"
        else:
            new = base
        if new != text:
            tgt.write_text(new, encoding="utf-8")
            changed += 1

    print(f"backlinks: scanned {len(files)} file(s), updated {changed}")


if __name__ == "__main__":
    main()
