#!/usr/bin/env python3
"""Inject the exemplar field-record after each profile's Profile line (pre-render).

The Typst filter has no per-chapter frontmatter, so this carries the gazetteer
field-record into the body. For each exemplar it reads the record fields and
writes a marker-delimited raw `#fg-record(...)` Typst block right after the
`*Profile: ...*` line. The glyph-led key/value record renders in the PDF; the
HTML wiki ignores the raw block (the web build reads frontmatter directly).

Field set (design system: cube/pen-nib/calendar/users/hourglass/stack/copyright):
  medium    <- record.medium   (else a label for the `medium` code)
  designer  <- designer
  published <- year
  players   <- record.players
  format    <- record.format
  substrate <- record.substrate
  licence   <- record.licence
Only fields that have a value are shown. Idempotent; a Quarto pre-render step.
"""
import pathlib
import re

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
EX = ROOT / "content" / "exemplars"
START = "<!-- EXEMPLAR-RECORD:START (generated by scripts/exemplar_record.py — do not edit by hand) -->"
END = "<!-- EXEMPLAR-RECORD:END -->"
BLOCK_RE = re.compile(r"\n*" + re.escape(START) + r".*?" + re.escape(END), re.S)
PROFILE_RE = re.compile(r"^\*Profile:.*\*[ \t]*$", re.M)
FM_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)

MEDIUM_LABEL = {
    "tabletop": "Tabletop game", "live-game": "Live game",
    "puzzle-hunt": "Puzzle hunt", "video-game": "Video game",
}
# (frontmatter source, glyph) in display order; designer/year are top-level,
# the rest live under a `record:` map.
ROWS = [
    ("medium", "cube"), ("designer", "pen-nib"), ("published", "calendar-blank"),
    ("players", "users-three"), ("format", "hourglass-simple"),
    ("substrate", "stack"), ("licence", "copyright"),
]


def tstr(s):
    """A Typst string literal."""
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    changed = 0
    for q in sorted(EX.glob("*.qmd")):
        if q.name == "index.qmd":
            continue
        text = q.read_text(encoding="utf-8")
        base = BLOCK_RE.sub("", text)
        fm = FM_RE.match(base)
        meta = (yaml.safe_load(fm.group(1)) if fm else None) or {}
        rec = meta.get("record") or {}
        values = {
            "medium": rec.get("medium") or MEDIUM_LABEL.get(meta.get("medium") or ""),
            "designer": rec.get("designer") or meta.get("designer"),
            "published": rec.get("published") or meta.get("year"),
            "players": rec.get("players"),
            "format": rec.get("format"),
            "substrate": rec.get("substrate"),
            "licence": rec.get("licence"),
        }
        pairs = [f"({tstr(g)}, {tstr(values[k])})" for k, g in ROWS if values.get(k)]
        prof = PROFILE_RE.search(base)

        if prof and pairs:
            tail = "," if len(pairs) == 1 else ""
            call = "```{=typst}\n#fg-record((" + ", ".join(pairs) + tail + "))\n```"
            block = f"{START}\n{call}\n{END}"
            i = prof.end()
            new = base[:i] + "\n\n" + block + "\n\n" + base[i:].lstrip("\n")
        else:
            new = base

        new = re.sub(r"\n{3,}", "\n\n", new)
        if not new.endswith("\n"):
            new += "\n"
        if new != text:
            q.write_text(new, encoding="utf-8")
            changed += 1
    print(f"exemplar-record: scanned exemplars, updated {changed}")


if __name__ == "__main__":
    main()
