#!/usr/bin/env python3
"""Inject the print specimen-line tags after each article's Silhouette (pre-render).

The Typst filter runs over the whole merged book and has no per-article
frontmatter, so we carry the opener tags into the body here. For each article we
read the lead effect (`facets.effects[0]`), lead problem (`facets.problems[0]`),
its `media` list, and the family (from the directory), and write a
marker-delimited `::: {.specimen-line ...}` div right after the Silhouette line.

filters/field-guide.lua renders that div as `#fg-tags()` for the PDF; the HTML
wiki ignores the empty div (the web build reads frontmatter directly). The full
facet lists stay in the Keys. See the design system's print-article-tags.md.

Idempotent: re-running with unchanged frontmatter is byte-identical. Runs as a
Quarto pre-render step (see _quarto.yml), alongside backlinks/keys/glossary.
"""
import pathlib
import re

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
ART = ROOT / "content" / "articles"
START = "<!-- SPECIMEN-TAGS:START (generated by scripts/specimen_tags.py — do not edit by hand) -->"
END = "<!-- SPECIMEN-TAGS:END -->"
# strip any prior block, including the blank line(s) that precede it
BLOCK_RE = re.compile(r"\n*" + re.escape(START) + r".*?" + re.escape(END), re.S)
# tolerate a trailing cross-reference anchor appended by scripts/xref_anchors.py
SIL_RE = re.compile(r"^\*Silhouette:.*\*(?:\[\]\{#[^}]*\})?[ \t]*$", re.M)
FM_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)

# frontmatter media code -> media glyph name (assets/icons/media/<name>-thin.svg)
MEDIA = {
    "interactive-fiction": "if", "live-game": "live",
    "tabletop": "tabletop", "puzzle-hunt": "hunt",
}
# article directory -> family key (matches the `fam` dict in typst/field-guide.typ)
FAMILY = {
    "structure-pacing": "structure", "puzzles-clues-information": "puzzles",
    "story-character-voice": "story", "players-social-dynamics": "players",
    "space-props-materiality": "space", "systems-mechanics": "systems",
}


def first(x):
    return x[0] if isinstance(x, list) and x else None


def main() -> None:
    changed = 0
    for q in sorted(ART.glob("*/*.qmd")):
        text = q.read_text(encoding="utf-8")
        base = BLOCK_RE.sub("", text)  # remove any previously injected block

        fm = FM_RE.match(base)
        meta = (yaml.safe_load(fm.group(1)) if fm else None) or {}
        facets = meta.get("facets") or {}
        effect = first(facets.get("effects"))
        problem = first(facets.get("problems"))
        media = [MEDIA[m] for m in (meta.get("media") or []) if m in MEDIA]
        family = FAMILY.get(q.parent.name)
        sil = SIL_RE.search(base)

        if sil and family and (effect or problem):
            attrs = []
            if effect:
                attrs.append(f'effect="{effect}"')
            if problem:
                attrs.append(f'problem="{problem}"')
            if media:
                attrs.append(f'media="{",".join(media)}"')
            attrs.append(f'family="{family}"')
            block = f'{START}\n::: {{.specimen-line {" ".join(attrs)}}}\n:::\n{END}'
            i = sil.end()
            new = base[:i] + "\n\n" + block + "\n\n" + base[i:].lstrip("\n")
        else:
            new = base  # no facets / no silhouette: leave the block stripped

        new = re.sub(r"\n{3,}", "\n\n", new)
        if not new.endswith("\n"):
            new += "\n"
        if new != text:
            q.write_text(new, encoding="utf-8")
            changed += 1
    print(f"specimen-tags: scanned articles, updated {changed}")


if __name__ == "__main__":
    main()
